EDGPATRON-92: Replace CompletableFuture with Future fixing spurious test failures
Timeout tests like MainVerticleTest.testPlaceInstanceHoldRequestTimeout have spurious test failures because CompletableFuture and Future may block each other:

```
12:46:48 INFO  MockOkapi            Waiting for 6000 ms before continuing
12:46:51 ERROR PatronHandler        Exception calling OKAPI
io.vertx.core.VertxException: Connection was closed
12:46:51 ERROR ?                    io.vertx.core.VertxException: Connection was closed
12:46:51 DEBUG Wire                  << "HTTP/1.1 500 Internal Server Error[\r][\n]"
12:46:51 DEBUG Wire                  << "content-type: application/json[\r][\n]"
12:46:51 DEBUG Wire                  << "content-length: 62[\r][\n]"
12:46:51 DEBUG Wire                  << "[\r][\n]"
12:46:51 DEBUG aultClientConnection Receiving response: HTTP/1.1 500 Internal Server Error
```

```
[ERROR]   MainVerticleTest.testPlaceItemHoldRequestTimeout:999 1 expectation failed.
Expected status code <408> but was <500>.
```

Solution: Replace CompletableFuture with Future